In [64]:
file = '''My Name Is" is a song by American rapper Eminem from his second album The Slim Shady LP (1999).
It is also the opening song and lead single of the album. The song samples British singer Labi Siffre's 1975 track "I Got The..." as a bass and guitar riff played by British pop rock duo Chas & Dave.
The song was ranked at #26 on "VH1's 100 Greatest Songs of the '90s".
"My Name Is" was also ranked #6 on Q Magazine's "1001 Best Songs Ever".[3] "My Name Is" peaked at number 36 on the Billboard Hot 100, becoming Eminem's first top 40 hit there. Outside the United States
"My Name Is" peaked within the top ten of the charts in Iceland, New Zealand, Norway, Ireland, and United Kingdom.
The song was placed at number 39 by Rolling Stone on their list of "100 Greatest Hip-Hop songs of all time" in April 2016.
The recording garnered Eminem his first Grammy Award for Best Rap Solo Performance at the 42nd Grammy Awards in 2000.
Background On the first day of recording, Eminem and Dr. Dre finished "My Name Is" in an hour. The song contains a sample of Labi Siffre's track "I Got The...". Siffre, who is openly gay, said in a 2012 interview that he refused to clear the sample until sexist and homophobic lyrics were removed from the song: "Dissing the victims of bigotry – women as bitches, homosexuals as faggots – is lazy writing. Diss the bigots not their victims.
The original uncensored version of the song with the aforementioned offending lyrics is mistakenly included on the compilation The Source Hip Hop Music Awards 1999. The bass and guitar riff used in the sample was performed by Siffre's session musicians Chas Hodges and Dave Peacock, who later became the duo Chas & Dave.
"My Name Is" is written in the key of F major.[8] Famous names referenced in the song include Nine Inch Nails,
the Spice Girls, and Pamela Anderson (Pamela Lee).
Music video The video premiered on MTV Total Request Live on January 21, 1999. It was directed by Phillip Atwell, who would later direct music videos for several other Eminem songs, including "The Real Slim Shady", "Stan", "Lose Yourself", and "Just Lose It".
The video starts out with a stereotypical redneck family watching television, who then come across a show starring "Marshall Mathers" (Eminem's real name). As the video goes on, Eminem parodies several TV shows and movies. He also imitates then-President of the United States Bill Clinton, Johnny Carson, a porn star, and others. Basketball player Gheorghe Mureșan has a cameo appearance as a ventriloquist with Eminem being used as the dummy in the scene. Dr. Dre, the song's producer, also has a cameo as a doctor.
It also features a Monica Lewinski lookalike, and Eminem imitating a chemistry teacher. Eminem is seen wearing a red tuxedo in some parts of the video, something that he would pay homage to in his 2020 single “Gnat”, 21 years after “My Name Is” was originally released.
The video was ranked #71 in NME's 100 Greatest Music Videos.[10] As of 2019, the music video has been replaced on all official sites (including the official Eminem YouTube account and MTV's holding accounts) with alternative lyrics online making it more advertiser friendly.
Lines such as, "Well, since age 12, I felt like I'm someone else 'Cause I hung my original self from the top bunk with a belt," are replaced with "Since age 12 I felt like a caged elf Who stayed to himself in one space, chasing his tail," also with lines referencing ripping Pamela Lee's breasts off replaced with ripping her lips off and kissing them, saying how they feel soft like silicon.'''

In [65]:
import tensorflow as tf
from tensorflow import keras
from keras.preprocessing.text import Tokenizer

In [66]:
token = Tokenizer()
token.fit_on_texts([file])

In [67]:
len(token.word_index)

332

In [68]:
input_sequence = []
for sentence in file.split('\n'):
  sequence = token.texts_to_sequences([sentence])[0]

  for i in range(1,len(sequence)):
    input_sequence.append(sequence[:i+1])

In [69]:
max([len(i) for i in input_sequence])

86

In [70]:
from keras.preprocessing.sequence import pad_sequences
pad = pad_sequences(input_sequence,maxlen=86,padding='pre')

In [71]:
pad

array([[  0,   0,   0, ...,   0,  13,  11],
       [  0,   0,   0, ...,  13,  11,   4],
       [  0,   0,   0, ...,  11,   4,   4],
       ...,
       [  0,   0,   0, ..., 329, 330, 331],
       [  0,   0,   0, ..., 330, 331,  43],
       [  0,   0,   0, ..., 331,  43, 332]], dtype=int32)

In [72]:
x = pad[:,:-1]
y = pad[:,-1]
y,x

(array([ 11,   4,   4,   2,   8,  17,  94,  95,   9,  26,  22,  96,  44,
          1,  45,  46,  97,  27,   4,  16,   1,  98,   8,   3,  99,  47,
          5,   1,  44,   1,   8, 100,  48, 101,  49,  28, 102,  50,  19,
         51,   1,  10,   2,  52,   3,  53,  54, 103,  17,  48, 104, 105,
         55,  29,  30,   8,  14,  31,  23, 106,   7, 107,  24,  32,  25,
          5,   1, 108,  11,   4,  14,  16,  31, 109,   7, 110, 111, 112,
         56,  25, 113, 114,  13,  11,   4,  57,  23,  58, 115,   7,   1,
        116, 117,  24, 118,  59,  33,  34, 119, 120, 121, 122,   1,  35,
         60,  11,   4,  57, 123,   1,  34, 124,   5,   1, 125,   6, 126,
        127, 128, 129, 130,   3,  35, 131,   8,  14, 132,  23,  58, 133,
         17, 134, 135,   7,  61, 136,   5,  24,  32,  62,  63,  25,   5,
         64, 137,   6, 138, 139,  65, 140,   9,  22,  33,  66, 141,  67,
         56, 142, 143, 144,  23,   1, 145,  66,  68,   6, 146,   7,   1,
         33, 148,   5,  65,   9,   3,  69,  70, 149

In [73]:
x.shape

(612, 85)

In [74]:
y.shape

(612,)

In [75]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes = 338)

In [76]:
y.shape

(612, 338)

In [77]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [78]:
from tensorflow.keras import Sequential
from keras.layers import LSTM, Embedding, Dense

In [79]:
model =  Sequential()
model.add(Embedding(333,100,input_length=85))
model.add(LSTM(150))
model.add(Dense(338,activation = 'softmax'))

In [80]:
model.compile(loss = 'categorical_crossentropy',optimizer = 'adam', metrics = ['accuracy'])


In [81]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 85, 100)           33300     
                                                                 
 lstm_4 (LSTM)               (None, 150)               150600    
                                                                 
 dense_4 (Dense)             (None, 338)               51038     
                                                                 
Total params: 234938 (917.73 KB)
Trainable params: 234938 (917.73 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [82]:
model.fit(x,y,epochs = 100)

Epoch 1/100
20/20 [==============================] - 6s 145ms/step - loss: 5.7784 - accuracy: 0.0474
Epoch 2/100
20/20 [==============================] - 4s 222ms/step - loss: 5.5603 - accuracy: 0.0621
Epoch 3/100
20/20 [==============================] - 3s 144ms/step - loss: 5.4223 - accuracy: 0.0621
Epoch 4/100
20/20 [==============================] - 3s 144ms/step - loss: 5.3886 - accuracy: 0.0621
Epoch 5/100
20/20 [==============================] - 3s 145ms/step - loss: 5.3663 - accuracy: 0.0621
Epoch 6/100
20/20 [==============================] - 5s 232ms/step - loss: 5.3332 - accuracy: 0.0621
Epoch 7/100
20/20 [==============================] - 3s 154ms/step - loss: 5.2851 - accuracy: 0.0621
Epoch 8/100
20/20 [==============================] - 3s 144ms/step - loss: 5.2293 - accuracy: 0.0637
Epoch 9/100
20/20 [==============================] - 3s 146ms/step - loss: 5.1242 - accuracy: 0.0735
Epoch 10/100
20/20 [==============================] - 4s 227ms/step - loss: 4.9824 - accura

In [133]:
import numpy as np

#for i in range(5):
#prediction>>
text = input('Enter the text:')
token_text = token.texts_to_sequences([text])[0]
pad_text = pad_sequences([token_text],maxlen = 85,padding = 'pre')

position = np.argmax(model.predict(pad_text))
for word,index in token.word_index.items():
  if index == position:
    #text = text + ' ' + word
    print(word)


Enter the text:my name is is written in the
1/1 [==============================] - 0s 38ms/step
key


1/1 [==============================] - 0s 35ms/step


In [104]:
token.word_index

{'the': 1,
 'a': 2,
 'and': 3,
 'is': 4,
 'of': 5,
 'in': 6,
 'on': 7,
 'song': 8,
 'eminem': 9,
 'as': 10,
 'name': 11,
 'with': 12,
 'my': 13,
 'was': 14,
 'video': 15,
 'also': 16,
 'by': 17,
 'it': 18,
 'i': 19,
 'who': 20,
 'music': 21,
 'his': 22,
 'at': 23,
 '100': 24,
 'songs': 25,
 'from': 26,
 '1999': 27,
 "siffre's": 28,
 'chas': 29,
 'dave': 30,
 'ranked': 31,
 'greatest': 32,
 'first': 33,
 'top': 34,
 'united': 35,
 'sample': 36,
 'he': 37,
 'to': 38,
 'lyrics': 39,
 'pamela': 40,
 'has': 41,
 'replaced': 42,
 'like': 43,
 'album': 44,
 'slim': 45,
 'shady': 46,
 'single': 47,
 'british': 48,
 'labi': 49,
 'track': 50,
 'got': 51,
 'bass': 52,
 'guitar': 53,
 'riff': 54,
 'duo': 55,
 'best': 56,
 'peaked': 57,
 'number': 58,
 "eminem's": 59,
 'states': 60,
 'their': 61,
 'hip': 62,
 'hop': 63,
 'all': 64,
 'recording': 65,
 'grammy': 66,
 'for': 67,
 'awards': 68,
 'dr': 69,
 'dre': 70,
 'that': 71,
 'victims': 72,
 '–': 73,
 'original': 74,
 'used': 75,
 'later': 76,
 '2